import { Chapter } from '../types';

export const exportStoryToText = (title: string, chapters: Chapter[], genre?: string): void => {
  // Build the text content
  let textContent = '';
  
  // Add title and metadata
  textContent += `${title}\n`;
  textContent += `${'='.repeat(title.length)}\n\n`;
  
  if (genre) {
    textContent += `Genre: ${genre}\n\n`;
  }
  
  textContent += `Generated by Lumina Stories\n`;
  textContent += `${new Date().toLocaleDateString()}\n\n`;
  textContent += `${'='.repeat(50)}\n\n`;
  
  // Add each chapter
  chapters.forEach((chapter, index) => {
    textContent += `\n\nChapter ${index + 1}: ${chapter.title}\n`;
    textContent += `${'-'.repeat(chapter.title.length + 12)}\n\n`;
    textContent += `${chapter.content}\n`;
  });
  
  // Add footer
  textContent += `\n\n${'='.repeat(50)}\n`;
  textContent += `\nEnd of Story\n`;
  
  // Create blob and download
  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  
  // Create filename from title (sanitize it)
  const sanitizedTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  link.download = `${sanitizedTitle}_story.txt`;
  
  // Trigger download
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

